#!/usr/bin/env bash
set -uo pipefail

KIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$KIT_DIR/.." && pwd)"
MARKER="# Generated by shared-test-kit install.sh"
KIT_NAME="$(basename "$KIT_DIR")"
SOURCE_FOLDERS=("Linked_List" "Stack_and_Queue" "Binary_Tree" "Binary_Search_Tree")

has_source_structure() {
  local root="$1"
  local folder
  for folder in "${SOURCE_FOLDERS[@]}"; do
    if [[ ! -d "$root/$folder" ]]; then
      return 1
    fi
  done
  return 0
}

detect_source_root() {
  local preferred="$PROJECT_ROOT/Data-Structures"
  local child

  if has_source_structure "$preferred"; then
    printf '%s\n' "$preferred"
    return 0
  fi

  for child in "$PROJECT_ROOT"/*; do
    [[ -d "$child" ]] || continue
    [[ "$child" == "$KIT_DIR" ]] && continue
    if has_source_structure "$child"; then
      printf '%s\n' "$child"
      return 0
    fi
  done

  return 1
}

SOURCE_ROOT="$(detect_source_root || true)"
if [[ -z "$SOURCE_ROOT" ]]; then
  echo "Could not find a source root beside $KIT_DIR" >&2
  echo "Place $KIT_NAME beside the real source folder that contains Linked_List, Stack_and_Queue, Binary_Tree, and Binary_Search_Tree, then run this again." >&2
  exit 1
fi

ensure_overwritable() {
  local target="$1"
  if [[ -e "$target" ]] && ! grep -qF "$MARKER" "$target" 2>/dev/null; then
    echo "Refusing to overwrite existing file: $target" >&2
    echo "Move it aside or delete it first, then rerun ./$KIT_NAME/install.sh" >&2
    exit 1
  fi
}

write_test_wrapper() {
  local target="$PROJECT_ROOT/test"
  ensure_overwritable "$target"
  cat > "$target" <<EOF
#!/usr/bin/env bash
$MARKER
set -uo pipefail
ROOT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
"\$ROOT_DIR/$KIT_NAME/test" "\$@"
exit \$?
EOF
  chmod 755 "$target"
}

write_runner_wrapper() {
  local target="$PROJECT_ROOT/run_ds_tests.sh"
  ensure_overwritable "$target"
  cat > "$target" <<EOF
#!/usr/bin/env bash
$MARKER
set -uo pipefail
ROOT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
"\$ROOT_DIR/$KIT_NAME/run_ds_tests.sh" "\$@"
exit \$?
EOF
  chmod 755 "$target"
}

write_test_wrapper
write_runner_wrapper

LEGACY_DSTEST="$PROJECT_ROOT/dstest"
if [[ -e "$LEGACY_DSTEST" ]] && grep -qF "$MARKER" "$LEGACY_DSTEST" 2>/dev/null; then
  rm -f "$LEGACY_DSTEST"
fi

echo "Installed wrappers in: $PROJECT_ROOT"
echo "Detected source root: $SOURCE_ROOT"
echo "Use:"
echo "  ./test list 1"
